### PR TITLE
Fix display bug for electric battery

### PR DESCRIPTION
**Pull request by minhki95**
Fixes parts of #120

### CODE REVIEW

**Comment by minhki95** [comment]
For the future one could think about a more efficient way to fetch the battery results. Right now retrieving them is rather tedious and needs some insight into the data and how it is structured, because the battery is a nested dictionary with input, output and capacity results of the battery inside it.

**Comment by Bachibouzouk** [comment]
> For the future one could think about a more efficient way to fetch the battery results.

this is what was done in #121 I think

**Comment by Bachibouzouk** [comment]
Before we merge this PR I would like to have the approval of @FredericHirschmueller that the capacity graph is displaying what is expected (I updated the online api with the changes from this PR)

**Comment by minhki95** [comment]
> this is what was done in #121 I think

Huh, even though I pulled this is not in my local repo, weird.

**Comment by Bachibouzouk** [comment]
> > this is what was done in #121 I think
> 
> Huh, even though I pulled this is not in my local repo, weird.

It was not merged yet, I forgot, sorry

**Pull request merged**
